<a href="https://colab.research.google.com/github/mojahid-t17/Machine-Learning/blob/main/4_Linear_algebra_for_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 - Representing and Solving System of Linear Equations using Matrices


###Solving Systems of Linear Equations using Matrices
Linear systems with two equations are easy to solve manually, but preparing for more complicated cases, you will investigate some solution techniques.

NumPy linear algebra package provides quick and reliable way to solve the system of linear equations using function np.linalg.solve(A, b). Here
 is a matrix, each row of which represents one equation in the system and each column corresponds to the variable
,
. And
 is a 1-D array of the free (right side) coefficients. More information about the np.linalg.solve()

In [ ]:
import numpy as np

In [ ]:
# -x1+3x2=7, 3x1+2x2=1
A=np.array([[-1, 3],
            [3, 2]
           ] , dtype=np.dtype(float))
b=np.array([7,1] ,dtype=np.dtype(float))
print(A)
print(b)

[[-1.  3.]
 [ 3.  2.]]
[7. 1.]


In [ ]:
#check the shape of A and b
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

# print(f"Shape of A: {np.shape(A)}")
# print(f"Shape of A: {np.shape(b)}")

Shape of A: (2, 2)
Shape of b: (2,)


In [ ]:
sol=np.linalg.solve(A,b)
sol

array([-1.,  2.])

In [ ]:
#Evaluating Determinant of a Matrix
print(f"the determinant of A matrix is: {np.linalg.det(A):.2f}")

the determinant of A matrix is: -11.00


In [ ]:
#  System of Linear Equations with No Solutions if det(A)=0
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")


Determinant of matrix A_2: 0.00


In [ ]:
# System of Linear Equations with Infinite Number of Solutions
A3=np.array([
    [-1, 3],
    [3,-9]
])
b3=np.array([7, -21])

In [ ]:
x2=np.hstack((A,b3.reshape(2,1)))
x2

array([[ -1.,   3.,   7.],
       [  3.,   2., -21.]])

#Matrix multiplication
Mathematically, matrix multiplication is defined only if number of the columns of matrix A is equal to the number of the rows of matrix B
mXn =nXp

In [ ]:
A=np.array([
    [2,4,5],
    [3,6,3],
])          #dimention 2X3
B=np.array([
    [1,2,3],
    [4,3,6],
    [4,2,7]
])         #dimention 3X2
np.matmul(A,B)

array([[38, 26, 65],
       [39, 30, 66]])

In [ ]:
A@B   # @ only works with numpy array

array([[38, 26, 65],
       [39, 30, 66]])

In [ ]:
#  Scalar Multiplication and Sum of Vectors
x = [1, -2, -5]
y = [4, 3, -1]

In [ ]:
def dot(x, y):
    s=0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

In [ ]:

print("The dot product of x and y is", dot(x, y))

The dot product of x and y is 3


In [ ]:
# t product is very a commonly used operator, so NumPy linear algebra package provides quick way to calculate it using function np.dot():
np.dot(x,y)

3

In [ ]:
# A=(2x1 + 4x2 + 5=0)
# B=(5x1 + 2x2 + 9)
#calculate the dot product of the two vector A and B

In [ ]:
# soln:
A=np.array([2, 4, 5])
B=np.array([5, 2, 9])
np.dot(A,B)

63

In [ ]:
# also doing this dot product by @
A@B

63

In [ ]:
# Define three vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(np.dot(A, B))
print(A@B)

32
32


In [ ]:
# distance from origin -> euclidean norm
# Define an n-dimensional vector A
A = np.array([1, 2, 3, 4, 5,6,7,8,9,10,11,112,12])
# Calculate the Euclidean distance from the origin
Distance=np.linalg.norm(A)
Distance

114.86513831445988

In [ ]:
# to find euclidean distance in n-D
# A and B are two vector , the distance of this two line is root over |A-B|
import numpy as np

# Define two n-dimensional vectors A and B
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

# Calculate the difference vector
difference = A - B

difference


array([-5, -5, -5, -5, -5])

In [ ]:
print(f"the distance of A and B is: {np.linalg.norm(difference)}")

the distance of A and B is: 11.180339887498949
